{{- if not .Values.configuration.agentOverride.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "t2ps-chatbot-llm.fullname.agent.config" . }}
  namespace: {{ include "t2ps-chatbot-llm.namespace" . }}
  labels:
    {{- include "t2ps-chatbot-llm.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
data:
  agent.yaml: |-
    {{- mustMergeOverwrite (.Files.Get "files/default-agent.yaml" | fromYaml) .Values.configuration.agent | toYaml | nindent 4 }}
{{- end }}
